### ISSUE TITLE
About close source and the future plan of this project

### ISSUE THREAD

**Issue by ultranity** [sophosia/sophosia#142]
Hey thanks for your work on a more customizable reference manager as a Zotero alternative, I have once fetched the source code of sophosia and tried to fix some css and arxiv loading issue, but sadly found that this project become close sourced two weeks ago.

It's of cource ok to make it a closed source project, but it might be easier to develop a good software if it could get community contributions? And what's the plan for this project next?

**Comment by HuntFeng** [comment]
Hi, thank you very much for your contribution! I really appreciate it!

Unfortunately our team is not good at marketing. Starting from two years ago Sophosia (and its beta version) only received 2 contributions (and  you are one of them). We decided to close source the project and premium features will be developed to support our further development. 

Meanwhile, new releases will be released every week. If you have any ideas or bugs to report, open an issue and we will follow up with you!

Again, thank you very much for your support! I hope Sophosia can help you through out your research career.

**Comment by HuntFeng** [comment]
Ah, I forgot the most important thing. Sophosia comes with the plugin system, you are welcome to write any plugins you like.

Currently the plugin system is still in its alpha stage due to lack of human powers, follow our dev if you like.

**Comment by HuntFeng** [comment]
For people randomly found this issue, I have changed my mind, the project is now open source 🎉🎉
