### ISSUE TITLE
Registering New Account Broken

### ISSUE THREAD

**Issue by Docfips** [sophosia/sophosia#160]
Good evening,

I just found out about this app and I'm really enjoying it so far.

However, I've tried to sign up for a new account, using all three ways, and the app never recognizes my SSO, and then when I tried to register using email only, I never received an email to confirm.

**Comment by HuntFeng** [comment]
Will investigate this soon. For now (2024 Aug) there is no need to register account, all functionalities are free to use.

The account registration is only for me to estimate number of users so I can select right services to deploy any future premium plugins/features.
