### ISSUE TITLE
Unable to update meta using this DOI

### ISSUE THREAD

**Issue by HuntFeng** [sophosia/sophosia#165]
Update meta using 10.1023/A:1013212916645, or https://doi.org/10.1023/A:1013212916645 throws error

TypeError: o.toLowerCase is not a function. (In 'o.toLowerCase()', 'o.toLowerCase' is undefined

**Comment by Malove98** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.

**Comment by HuntFeng** [comment]
Turns out the title attribute of these dois is empty array...
