### ISSUE TITLE
是个非常棒的项目！

### ISSUE THREAD

**Issue by xh542428798** [sophosia/sophosia#47]
以文件为中心，以做笔记为中心，是我非常想要的样子，感谢作者创造了这个东西。
试用之后，我感觉有一些问题：
1. doi导入数据，好像读取不到摘要，比如：10.1016/S0140-6736(19)30956-0。如果可以的话，直接识别enw或者bib格式就完美了，从剪切版导入。
2. 这个超链接太敏感了，我想选文字的，但是只要中间有超链接，就会跳出来，打断我选择文本。感觉要是按住ctrl再显示超链接会更好。
3. 在pdf里的笔记，如果可以通过拖拽放到markdown里面，生成笔记并配上链接就完美了。

希望这个工具能越来越好！

**Comment by HuntFeng** [comment]
非常好的建议！都做了

- [ ] Improve doi fetch ability
- [ ] Better behavior of pdf internal link peeker
- [ ] Able to drag pdf annotations and drop them into notes
