### ISSUE TITLE
Better PDF internal link peeker behavior

### ISSUE THREAD

**Issue by HuntFeng** [sophosia/sophosia#50]
Peeker pops up when user trying to select text. Might need to add some extra action from user to trigger the pop up.

1. User click link to open peeker, double click the link to navigate.
2. User press ctrl and hover on link to open peeker, click the link to navigate.
3. Maybe other options?

**Comment by GedeonIsezerano** [comment]
The new pdf internal link peeker is: left click to navigate, right click to open the picker.
